[package]
name = "quadboy"
version = "0.1.0"
edition = "2024"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_ecs = "0.15.3"
macroquad = "0.4.13"
macroquad-profiler = "0.2.0"

[patch.crates-io]
macroquad = { git = "https://github.com/not-fl3/macroquad" }
